#!/usr/bin/env bash
set -euo pipefail ${DEBUGSH+-x}

# Poor man’s arg parse :/
arg="${1-}"
: "${MONOREPO_NAME:=core}"

if [[ "$arg" == "" ]]; then
	if [[ -d "$MONOREPO_NAME" && "$arg" != "--continue" ]]; then
		>&2 echo "monorepo directory $MONOREPO_NAME already exists"
		exit 1
	fi
	mkdir "$MONOREPO_NAME"
	cd "$MONOREPO_NAME"
	git init
elif [[ "$arg" != "--continue" ]]; then
	>&2 echo "Unexpected argument: $arg"
	>&2 echo
	>&2 echo "Usage: $0 [--continue]"
	exit 1
elif [[ ! -d "$MONOREPO_NAME" ]]; then
	>&2 echo "Asked to --continue, but monorepo directory $MONOREPO_NAME doesn’t exist"
	exit 1
else
	cd "$MONOREPO_NAME"
	if git status --porcelain | grep . ; then
		>&2 echo "Git status shows pending changes in the repo. Cannot --continue."
		exit 1
	fi
	# There isn’t anything special about --continue, really.
fi

empty_tree="$(git hash-object -t tree /dev/null)"

# Note this is top-level in the script so it’s reading from the script’s stdin
while IFS=$'\r'"$IFS" read -r repourl reponame repopath; do
    if [[ -z "$repopath" ]]; then
        repopath="$reponame"
    fi

    git remote add "$reponame" "$repourl"
    git config --add "remote.$reponame.fetch" "+refs/tags/*:refs/tags/$reponame/*"
    git config "remote.$reponame.tagOpt" --no-tags
    git fetch --atomic "$reponame"
    
    git branch -r --no-color --list "$reponame/*" --format "%(refname:lstrip=3)" | while read -r branch ; do
        if ! git show-ref --verify --quiet "refs/heads/$branch"; then
            git branch -- "$branch" "$(printf "Root commit for monorepo branch %s" "$branch" | git commit-tree "$empty_tree")"
        fi
        git symbolic-ref HEAD "refs/heads/$branch"
        git reset
        
        git merge --strategy=ours "$reponame/$branch" --allow-unrelated-histories --no-commit --no-ff
        git read-tree --prefix "$repopath" "$reponame/$branch"
        git commit -m "Merge $reponame/$branch" --allow-empty
    done
done

git checkout .

# Copyright © 2020, 2022 Hraban Luyat
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, version 3 of the License.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
