#!/usr/bin/env bash
set -euo pipefail ${DEBUGSH+-x}

if ((BASH_VERSINFO[0] > 4 || (BASH_VERSINFO[0] == 4 && BASH_VERSINFO[1] >= 4))); then
	shopt -s inherit_errexit
fi
# Poor man’s arg parse :/

print-usage () {
    cat <<EOF
Usage:

    cat my-projects.txt | tomono

For more information, see the documentation at "https://tomono.0brg.net".
EOF
}

arg="${1-}"
case "$arg" in
	"")
		# Pass
		;;
	"--help" | "-h" | "help")
		print-usage
		exit 0
		;;
	*)
		print-usage
		exit 1
		;;
esac
: "${MONOREPO_NAME:=core}"

if [[ ! -a "$MONOREPO_NAME" ]]; then
    mkdir "$MONOREPO_NAME"
    cd "$MONOREPO_NAME"
    git init
else
    cd "$MONOREPO_NAME"
    if git status --porcelain | grep . ; then
        >&2 cat <<EOF
A repository already exists in $MONOREPO_NAME, which is fine, but 'git status'
shows pending changes, which is dangerous. Commit these changes or remove them
somehow, and try again.
EOF
        exit 1
    fi
fi

empty_tree="$(git hash-object -t tree /dev/null)"

# Note this is top-level in the script so it’s reading from the script’s stdin
while IFS=$'\r'"$IFS" read -r repourl reponame repopath; do
    if [[ -z "$repopath" ]]; then
        repopath="$reponame"
    fi

    if git config "remote.${reponame}.url" >/dev/null; then
        continue
    fi

    git remote add "$reponame" "$repourl"
    git config --add "remote.$reponame.fetch" "+refs/tags/*:refs/tags/$reponame/*"
    git config "remote.$reponame.tagOpt" --no-tags
    git fetch --atomic "$reponame"
    
    git branch -r --no-color --list "$reponame/*" --format "%(refname:lstrip=3)" | while read -r branch ; do
        if ! git show-ref --verify --quiet "refs/heads/$branch"; then
            tree="$(git commit-tree \
                "$empty_tree" \
                -m "Root commit for monorepo branch $branch")"
            git branch -- "$branch" "$tree"
        fi
        git symbolic-ref HEAD "refs/heads/$branch"
        git reset -q
        
        git read-tree --prefix "$repopath" "refs/remotes/$reponame/$branch"
        tree="$(git write-tree)"
        commit="$(git commit-tree \
            "$tree" \
            -p "$branch" \
            -p "refs/remotes/$reponame/$branch" \
            -m "Merge $reponame/$branch")"
        git reset -q "$commit"
    done
done

git checkout .

# Copyright © 2020, 2022, 2023 Hraban Luyat
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, version 3 of the License.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
